#!/usr/bin/env bash
# OpenShip — interactive onboarding. Configures everything from the console and
# wires up your AI tool. Run: openship init
. "$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/lib.sh"

# --- colors (disabled when not a TTY or NO_COLOR set) ---
if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  B=$'\033[1m'; D=$'\033[2m'; R=$'\033[0m'
  CY=$'\033[36m'; GR=$'\033[32m'; YL=$'\033[33m'; MG=$'\033[35m'
else B=; D=; R=; CY=; GR=; YL=; MG=; fi
RULE="${CY}────────────────────────────────────────────${R}"

ask() { local __v="$1" __p="$2" __d="$3" __a
  printf '  %s%s%s' "$CY" "$__p" "$R"; [ -n "$__d" ] && printf ' %s[%s]%s' "$D" "$__d" "$R"
  printf ' %s›%s ' "$B" "$R"; read -r __a || __a=""; [ -z "$__a" ] && __a="$__d"; printf -v "$__v" '%s' "$__a"; }
ask_yn() { local __v="$1" __p="$2" __d="$3" __a
  printf '  %s%s%s %s[%s]%s %s›%s ' "$CY" "$__p" "$R" "$D" "$([ "$__d" = y ] && echo 'Y/n' || echo 'y/N')" "$R" "$B" "$R"
  read -r __a || __a=""; [ -z "$__a" ] && __a="$__d"; case "$__a" in [Yy]*) printf -v "$__v" y;; *) printf -v "$__v" n;; esac; }
ok()      { printf '  %s✓%s %s\n' "$GR" "$R" "$1"; }
section() { printf '\n  %s  %s%s%s\n' "$1" "$B" "$2" "$R"; }

# --- header ---
printf '\n  %s%s⛵  OpenShip%s\n' "$CY" "$B" "$R"
printf '  %sa git-native, agent-agnostic ship log for your work%s\n' "$D" "$R"
printf '  %s\n' "$RULE"

case "$(uname -s)" in
  Darwin) DEF_DONE="/System/Library/Sounds/Glass.aiff"; DEF_INPUT="/System/Library/Sounds/Funk.aiff" ;;
  *)      DEF_DONE=""; DEF_INPUT="" ;;
esac

section "📦" "Storage"
ask LOG_DIR "Log location" "$HOME/.openship"
LOG_DIR="${LOG_DIR/#\~/$HOME}"

section "🔔" "Notifications"
ask_yn PUSH "Phone push (ntfy)?" n
NTFY=""
if [ "$PUSH" = y ]; then
  RAND="$(head -c 6 /dev/urandom 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n')"
  ask NTFY "  ntfy topic (subscribe in the app)" "openship-${RAND:-changeme}"
fi
ask_yn SND "Sounds?" y
S_DONE=""; S_INPUT=""; [ "$SND" = y ] && { S_DONE="$DEF_DONE"; S_INPUT="$DEF_INPUT"; }
ask MIN "Notify gate (seconds)" "60"

section "👋" "Briefing"
ask DAYS "Window (days)" "7"
DEF_NAME="$(git config --global user.name 2>/dev/null | awk '{print $1}')"
ask FULLNAME "Your name" "$DEF_NAME"
DEF_USER="$(gh api user -q .login 2>/dev/null)"
ask GHUSER "GitHub handle" "$DEF_USER"
ask BANNER "Custom banner file (optional)" ""

# --- write config ---
CFG_DIR="$HOME/.config/openship"; CFG="$CFG_DIR/config.sh"; mkdir -p "$CFG_DIR" 2>/dev/null
cat > "$CFG" <<EOF
# OpenShip config — generated by 'openship init' on $(date +%Y-%m-%d)
OPENSHIP_LOG_DIR="$LOG_DIR"
OPENSHIP_MIN_SECONDS=$MIN
OPENSHIP_NTFY_TOPIC="$NTFY"
OPENSHIP_SOUND_DONE="$S_DONE"
OPENSHIP_SOUND_INPUT="$S_INPUT"
OPENSHIP_BANNER="$BANNER"
OPENSHIP_BRIEFING_DAYS=$DAYS
OPENSHIP_NAME="$FULLNAME"
OPENSHIP_USER="$GHUSER"
EOF
printf '\n'; ok "config → ${D}$CFG${R}"
mkdir -p "$LOG_DIR" 2>/dev/null && ok "log dir → ${D}$LOG_DIR${R}"

# --- openship on PATH ---
BINDIR=""; for d in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin; do case ":$PATH:" in *":$d:"*) [ -w "$d" ] && { BINDIR="$d"; break; };; esac; done
if [ -n "$BINDIR" ]; then
  ask_yn LINK "Add 'openship' to your PATH ($BINDIR)?" y
  [ "$LINK" = y ] && ln -sf "$OPENSHIP_HOME/bin/openship" "$BINDIR/openship" && ok "linked ${D}$BINDIR/openship${R}"
else
  printf '  %sℹ%s add to PATH: %sexport PATH="%s/bin:\$PATH"%s\n' "$YL" "$R" "$D" "$OPENSHIP_HOME" "$R"
fi

# --- agent ---
section "🤖" "Wire up your AI tool"
printf '     %s1%s Claude Code   %s2%s Codex   %s3%s opencode   %s4%s skip\n' "$B" "$R" "$B" "$R" "$B" "$R" "$B" "$R"
ask AGENT "choose" "1"
case "$AGENT" in
  1|claude*)   bash "$OPENSHIP_HOME/adapters/claude-code/install.sh" ;;
  2|codex*)    bash "$OPENSHIP_HOME/adapters/codex/install.sh" ;;
  3|opencode*) bash "$OPENSHIP_HOME/adapters/opencode/install.sh" ;;
  *)           printf '  %s—%s skipped agent wiring\n' "$D" "$R" ;;
esac

# --- done ---
printf '\n  %s\n' "${GR}────────────────────────────────────────────${R}"
printf '  %s%s⛵  All aboard.%s  OpenShip is ready.\n' "$GR" "$B" "$R"
printf '     try  %sopenship briefing%s   %sopenship idea "…"%s   %sopenship read%s\n\n' "$CY" "$R" "$CY" "$R" "$CY" "$R"
