#!/usr/bin/env bash
# OpenShip — interactive onboarding. Configures everything from the console and
# wires up your AI tool. Run: openship init
. "$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/lib.sh"

ask() { # ask <var> <prompt> <default>
  local __v="$1" __p="$2" __d="$3" __a
  printf '  %s' "$__p"; [ -n "$__d" ] && printf ' [%s]' "$__d"; printf ': '
  read -r __a || __a=""
  [ -z "$__a" ] && __a="$__d"
  printf -v "$__v" '%s' "$__a"
}
ask_yn() { # ask_yn <var> <prompt> <default y|n>
  local __v="$1" __p="$2" __d="$3" __a
  printf '  %s [%s]: ' "$__p" "$([ "$__d" = y ] && echo 'Y/n' || echo 'y/N')"
  read -r __a || __a=""
  [ -z "$__a" ] && __a="$__d"
  case "$__a" in [Yy]*) printf -v "$__v" 'y';; *) printf -v "$__v" 'n';; esac
}

echo
echo "  ⛵  OpenShip — setup"
echo "  A git-native, agent-agnostic ship log for your work."
echo

case "$(uname -s)" in
  Darwin) DEF_DONE="/System/Library/Sounds/Glass.aiff"; DEF_INPUT="/System/Library/Sounds/Funk.aiff" ;;
  *)      DEF_DONE=""; DEF_INPUT="" ;;
esac

ask LOG_DIR "Where should the ship log live?" "$HOME/.openship"
LOG_DIR="${LOG_DIR/#\~/$HOME}"

ask_yn PUSH "Enable phone push via ntfy.sh?" n
NTFY=""
if [ "$PUSH" = y ]; then
  RAND="$(head -c 6 /dev/urandom 2>/dev/null | od -An -tx1 2>/dev/null | tr -d ' \n')"
  ask NTFY "  ntfy topic (subscribe to it in the ntfy app)" "openship-${RAND:-changeme}"
fi

ask_yn SND "Enable notification sounds?" y
S_DONE=""; S_INPUT=""
[ "$SND" = y ] && { S_DONE="$DEF_DONE"; S_INPUT="$DEF_INPUT"; }

ask MIN "Only notify for tasks longer than N seconds" "60"
ask DAYS "How many days should the briefing look back?" "7"
ask BANNER "Path to an ASCII banner file for the briefing (blank = none)" ""

CFG_DIR="$HOME/.config/openship"; CFG="$CFG_DIR/config.sh"
mkdir -p "$CFG_DIR" 2>/dev/null
cat > "$CFG" <<EOF
# OpenShip config — generated by 'openship init' on $(date +%Y-%m-%d)
OPENSHIP_LOG_DIR="$LOG_DIR"
OPENSHIP_MIN_SECONDS=$MIN
OPENSHIP_NTFY_TOPIC="$NTFY"
OPENSHIP_SOUND_DONE="$S_DONE"
OPENSHIP_SOUND_INPUT="$S_INPUT"
OPENSHIP_BANNER="$BANNER"
OPENSHIP_BRIEFING_DAYS=$DAYS
EOF
echo
echo "  ✓ config written to $CFG"
mkdir -p "$LOG_DIR" 2>/dev/null && echo "  ✓ log dir ready at $LOG_DIR"

# put `openship` on PATH
BINDIR=""
for d in "$HOME/.local/bin" "/usr/local/bin"; do
  case ":$PATH:" in *":$d:"*) BINDIR="$d"; break;; esac
done
if [ -n "$BINDIR" ]; then
  ask_yn LINK "Symlink 'openship' into $BINDIR (on your PATH)?" y
  if [ "$LINK" = y ]; then
    mkdir -p "$BINDIR" 2>/dev/null
    ln -sf "$OPENSHIP_HOME/bin/openship" "$BINDIR/openship" && echo "  ✓ linked $BINDIR/openship"
  fi
else
  echo "  ℹ Add to PATH:  export PATH=\"$OPENSHIP_HOME/bin:\$PATH\""
fi

# agent adapter
echo
echo "  Which AI tool should I wire up?"
echo "     1) Claude Code     2) Codex     3) opencode     4) skip"
ask AGENT "  choose" "1"
case "$AGENT" in
  1|claude*)   bash "$OPENSHIP_HOME/adapters/claude-code/install.sh" ;;
  2|codex*)    bash "$OPENSHIP_HOME/adapters/codex/install.sh" ;;
  3|opencode*) bash "$OPENSHIP_HOME/adapters/opencode/install.sh" ;;
  *)           echo "  (skipped agent wiring)" ;;
esac

echo
echo "  ⛵  Done. Try:  openship briefing   ·   openship idea \"...\"   ·   openship read"
